export const Users = [
    {
      id:1,
      profilePicture: "/assets/persons/1.jpg",
      username: "Suhaib Mirza",
    },
    {
      id:2,
      profilePicture: "/assets/persons/2.jpg",
      username: "Jade Edwards",
    },
    {
      id:3,
      profilePicture: "/assets/persons/3.jpg",
      username: "Charlotte Stratton",
    },
    {
      id:4,
      profilePicture: "/assets/persons/4.jpg",
      username: "Tiffany Flair",
    },
    {
      id:5,
      profilePicture: "/assets/persons/5.jpg",
      username: "Adam Smith",
    },
    {
      id:6,
      profilePicture: "/assets/persons/6.jpg",
      username: "John Doe",
    },
    {
      id:7,
      profilePicture: "/assets/persons/7.jpg",
      username: "Will Jacks",
    },
    {
      id:8,
      profilePicture: "assets/persons/8.jpg",
      username: "Tim Richarson",
    },
    {
      id:9,
      profilePicture: "/assets/persons/9.jpg",
      username: "Kane Williams",
    },
    {
      id:10,
      profilePicture: "/assets/persons/10.jpg",
      username: "Amelia Kerr",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "/assets/posts/1.avif",
      date: "5 mins ago",
      userId:1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "/assets/posts/2.avif",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "/assets/posts/3.avif",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "/assets/posts/4.avif",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "/assets/posts/5.avif",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "/assets/posts/6.avif",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
        id: 7,
        desc: "Every moment is a fresh beginning.",
        photo: "/assets/posts/7.jpg",
        date: "2 days ago",
        userId: 7,
        like: 91,
        comment: 28,
      },
      {
        id: 8,
        desc: "Moment...",
        photo: "/assets/posts/8.jpg",
        date: "4 days ago",
        userId: 8,
        like: 67,
        comment: 22,
      },
      {
        id: 9,
        desc: "A fresh beginning..",
        photo: "/assets/posts/9.jpg",
        date: "6 days ago",
        userId: 9,
        like: 51,
        comment: 7,
      },
      {
        id: 10,
        photo: "/assets/posts/10.jpg",
        date: "1 week ago",
        userId: 10,
        like: 151,
        comment: 34,
      },
    
  ];